/**
 * Unit tests for config generator
 *
 * @group unit
 * @group targets
 */

import { describe, expect, it } from 'vitest';
import {
  generateArtkConfig,
  generateMinimalArtkConfig,
  generateConfigFromDetection,
  isValidTargetName,
  normalizeTargetName,
  generateEnvironmentUrls,
  generateArtkConfigWithResult,
  type ConfigGeneratorOptions,
  type ConfigTargetInput,
} from '../config-generator.js';

// =============================================================================
// Test Data
// =============================================================================

function createMockOptions(
  overrides?: Partial<ConfigGeneratorOptions>
): ConfigGeneratorOptions {
  return {
    projectName: 'test-project',
    targets: [
      {
        name: 'user-portal',
        path: '../frontend',
        type: 'react-spa',
        description: 'User Portal',
        environments: {
          local: { baseUrl: 'http://localhost:3000' },
          staging: { baseUrl: 'https://staging.example.com' },
        },
      },
    ],
    ...overrides,
  };
}

// =============================================================================
// generateArtkConfig Tests
// =============================================================================

describe('generateArtkConfig', () => {
  describe('header and structure', () => {
    it('should include ARTK header when comments enabled', () => {
      const config = generateArtkConfig(createMockOptions({ includeComments: true }));

      expect(config).toContain('# ARTK E2E Configuration');
      expect(config).toContain('# Generated by ARTK init');
    });

    it('should not include header when comments disabled', () => {
      const config = generateArtkConfig(createMockOptions({ includeComments: false }));

      expect(config).not.toContain('# ARTK E2E Configuration');
    });

    it('should include schema version', () => {
      const config = generateArtkConfig(createMockOptions());

      expect(config).toContain('schemaVersion: "2.0"');
    });
  });

  describe('project section', () => {
    it('should include project name', () => {
      const config = generateArtkConfig(
        createMockOptions({ projectName: 'my-project' })
      );

      expect(config).toContain('project:');
      expect(config).toContain('name: my-project');
    });

    it('should include project description when provided', () => {
      const config = generateArtkConfig(
        createMockOptions({ projectDescription: 'My test project' })
      );

      expect(config).toContain('description: My test project');
    });

    it('should not include description when not provided', () => {
      const config = generateArtkConfig(createMockOptions());

      const lines = config.split('\n');
      const projectSection = lines.slice(
        lines.findIndex((l) => l.includes('project:')),
        lines.findIndex((l) => l.includes('project:')) + 3
      );

      expect(projectSection.some((l) => l.includes('description'))).toBe(false);
    });
  });

  describe('targets section', () => {
    it('should include targets section', () => {
      const config = generateArtkConfig(createMockOptions());

      expect(config).toContain('targets:');
    });

    it('should include target properties', () => {
      const config = generateArtkConfig(createMockOptions());

      expect(config).toContain('- name: user-portal');
      expect(config).toContain('path: ../frontend');
      expect(config).toContain('type: react-spa');
      expect(config).toContain('description: User Portal');
    });

    it('should include target environments', () => {
      const config = generateArtkConfig(createMockOptions());

      expect(config).toContain('environments:');
      expect(config).toContain('local:');
      expect(config).toContain('baseUrl: http://localhost:3000');
      expect(config).toContain('staging:');
      expect(config).toContain('baseUrl: https://staging.example.com');
    });

    it('should include apiUrl when provided', () => {
      const config = generateArtkConfig(
        createMockOptions({
          targets: [
            {
              name: 'portal',
              path: './src',
              type: 'react-spa',
              environments: {
                local: {
                  baseUrl: 'http://localhost:3000',
                  apiUrl: 'http://localhost:4000/api',
                },
              },
            },
          ],
        })
      );

      expect(config).toContain('apiUrl: http://localhost:4000/api');
    });

    it('should include multiple targets', () => {
      const config = generateArtkConfig(
        createMockOptions({
          targets: [
            {
              name: 'frontend',
              path: './frontend',
              type: 'react-spa',
              environments: { local: { baseUrl: 'http://localhost:3000' } },
            },
            {
              name: 'admin',
              path: './admin',
              type: 'vue-spa',
              environments: { local: { baseUrl: 'http://localhost:3001' } },
            },
          ],
        })
      );

      expect(config).toContain('- name: frontend');
      expect(config).toContain('- name: admin');
    });
  });

  describe('defaults section', () => {
    it('should include defaults section', () => {
      const config = generateArtkConfig(createMockOptions());

      expect(config).toContain('defaults:');
    });

    it('should use first target as default when not specified', () => {
      const config = generateArtkConfig(createMockOptions());

      expect(config).toContain('target: user-portal');
    });

    it('should use specified default target', () => {
      const config = generateArtkConfig(
        createMockOptions({
          targets: [
            {
              name: 'first',
              path: './first',
              type: 'react-spa',
              environments: { local: { baseUrl: 'http://localhost:3000' } },
            },
            {
              name: 'second',
              path: './second',
              type: 'react-spa',
              environments: { local: { baseUrl: 'http://localhost:3001' } },
            },
          ],
          defaultTarget: 'second',
        })
      );

      expect(config).toContain('target: second');
    });

    it('should use default environment', () => {
      const config = generateArtkConfig(
        createMockOptions({ defaultEnvironment: 'staging' })
      );

      expect(config).toContain('environment: staging');
    });

    it('should use local as default environment when not specified', () => {
      const config = generateArtkConfig(createMockOptions());

      expect(config).toContain('environment: local');
    });
  });

  describe('auth section', () => {
    it('should not include auth section by default', () => {
      const config = generateArtkConfig(createMockOptions({ includeAuth: false }));

      // Check for auth section specifically (not auth timeout which is in timeouts section)
      expect(config).not.toContain('auth:\n  enabled:');
      expect(config).not.toContain('storageStateDir:');
    });

    it('should include auth section when enabled', () => {
      const config = generateArtkConfig(createMockOptions({ includeAuth: true }));

      expect(config).toContain('auth:');
      expect(config).toContain('enabled: true');
      expect(config).toContain('storageStateDir: .auth-states');
    });

    it('should use custom storage state directory', () => {
      const config = generateArtkConfig(
        createMockOptions({
          includeAuth: true,
          storageStateDir: 'custom-states',
        })
      );

      expect(config).toContain('storageStateDir: custom-states');
    });

    it('should include default role configuration', () => {
      const config = generateArtkConfig(createMockOptions({ includeAuth: true }));

      expect(config).toContain('roles:');
      expect(config).toContain('default:');
      expect(config).toContain('credentialsEnv:');
      expect(config).toContain('username: ARTK_USERNAME');
      expect(config).toContain('password: ARTK_PASSWORD');
    });

    it('should include OIDC comments when comments enabled', () => {
      const config = generateArtkConfig(
        createMockOptions({
          includeAuth: true,
          includeComments: true,
        })
      );

      expect(config).toContain('# Uncomment for OIDC authentication');
    });
  });

  describe('browser section', () => {
    it('should include browser section by default', () => {
      const config = generateArtkConfig(createMockOptions());

      expect(config).toContain('browsers:');
      expect(config).toContain('enabled:');
      expect(config).toContain('- chromium');
      expect(config).toContain('headless: true');
    });

    it('should not include browser section when disabled', () => {
      const config = generateArtkConfig(
        createMockOptions({ includeBrowserConfig: false })
      );

      expect(config).not.toContain('browsers:');
    });

    it('should include multiple browsers', () => {
      const config = generateArtkConfig(
        createMockOptions({ browsers: ['chromium', 'firefox', 'webkit'] })
      );

      expect(config).toContain('- chromium');
      expect(config).toContain('- firefox');
      expect(config).toContain('- webkit');
    });
  });

  describe('timeouts section', () => {
    it('should include timeouts section by default', () => {
      const config = generateArtkConfig(createMockOptions());

      expect(config).toContain('timeouts:');
      expect(config).toContain('default: 30000');
      expect(config).toContain('navigation: 60000');
      expect(config).toContain('auth: 120000');
    });

    it('should not include timeouts when disabled', () => {
      const config = generateArtkConfig(createMockOptions({ includeTimeouts: false }));

      expect(config).not.toContain('timeouts:');
    });
  });

  describe('YAML special characters', () => {
    it('should quote description with special characters', () => {
      const config = generateArtkConfig(
        createMockOptions({
          projectDescription: 'My project: with special characters!',
        })
      );

      expect(config).toContain('"My project: with special characters!"');
    });

    it('should not quote simple descriptions', () => {
      const config = generateArtkConfig(
        createMockOptions({ projectDescription: 'Simple description' })
      );

      expect(config).toContain('description: Simple description');
      expect(config).not.toContain('"Simple description"');
    });
  });
});

// =============================================================================
// generateMinimalArtkConfig Tests
// =============================================================================

describe('generateMinimalArtkConfig', () => {
  it('should generate minimal config', () => {
    const config = generateMinimalArtkConfig('my-project', '../frontend');

    expect(config).toContain('project:');
    expect(config).toContain('name: my-project');
    expect(config).toContain('targets:');
    expect(config).toContain('- name: main');
  });

  it('should use provided path', () => {
    const config = generateMinimalArtkConfig('project', './src');

    expect(config).toContain('path: ./src');
  });

  it('should use default react-spa type', () => {
    const config = generateMinimalArtkConfig('project', './src');

    expect(config).toContain('type: react-spa');
  });

  it('should use custom type', () => {
    const config = generateMinimalArtkConfig('project', './src', 'vue-spa');

    expect(config).toContain('type: vue-spa');
  });

  it('should include local environment only', () => {
    const config = generateMinimalArtkConfig('project', './src');

    expect(config).toContain('local:');
    expect(config).toContain('baseUrl: http://localhost:3000');
    expect(config).not.toContain('staging:');
    expect(config).not.toContain('production:');
  });

  it('should not include optional sections', () => {
    const config = generateMinimalArtkConfig('project', './src');

    expect(config).not.toContain('auth:');
    expect(config).not.toContain('browsers:');
    expect(config).not.toContain('timeouts:');
    expect(config).not.toContain('#'); // No comments
  });
});

// =============================================================================
// generateConfigFromDetection Tests
// =============================================================================

describe('generateConfigFromDetection', () => {
  it('should generate config from detected targets', () => {
    const config = generateConfigFromDetection('my-project', [
      {
        name: 'frontend',
        path: './frontend',
        type: 'react-spa',
        description: 'Main Frontend',
      },
    ]);

    expect(config).toContain('project:');
    expect(config).toContain('name: my-project');
    expect(config).toContain('- name: frontend');
    expect(config).toContain('path: ./frontend');
    expect(config).toContain('type: react-spa');
  });

  it('should include standard environments', () => {
    const config = generateConfigFromDetection('project', [
      { name: 'portal', path: './src', type: 'vue-spa' },
    ]);

    expect(config).toContain('local:');
    expect(config).toContain('baseUrl: http://localhost:3000');
    expect(config).toContain('staging:');
    expect(config).toContain('https://staging.portal.example.com');
    expect(config).toContain('production:');
    expect(config).toContain('https://portal.example.com');
  });

  it('should include multiple targets', () => {
    const config = generateConfigFromDetection('project', [
      { name: 'frontend', path: './frontend', type: 'react-spa' },
      { name: 'admin', path: './admin', type: 'angular' },
    ]);

    expect(config).toContain('- name: frontend');
    expect(config).toContain('- name: admin');
  });

  it('should include auth section', () => {
    const config = generateConfigFromDetection('project', [
      { name: 'app', path: './src', type: 'react-spa' },
    ]);

    expect(config).toContain('auth:');
  });

  it('should include comments', () => {
    const config = generateConfigFromDetection('project', [
      { name: 'app', path: './src', type: 'react-spa' },
    ]);

    expect(config).toContain('#');
  });
});

// =============================================================================
// isValidTargetName Tests
// =============================================================================

describe('isValidTargetName', () => {
  it('should validate lowercase-kebab-case names', () => {
    expect(isValidTargetName('user-portal')).toBe(true);
    expect(isValidTargetName('admin')).toBe(true);
    expect(isValidTargetName('my-app-frontend')).toBe(true);
  });

  it('should validate names starting with letter', () => {
    expect(isValidTargetName('a')).toBe(true);
    expect(isValidTargetName('abc123')).toBe(true);
  });

  it('should reject names starting with number', () => {
    expect(isValidTargetName('123app')).toBe(false);
    expect(isValidTargetName('1-app')).toBe(false);
  });

  it('should reject names starting with hyphen', () => {
    expect(isValidTargetName('-app')).toBe(false);
  });

  it('should reject uppercase letters', () => {
    expect(isValidTargetName('UserPortal')).toBe(false);
    expect(isValidTargetName('USER')).toBe(false);
  });

  it('should reject special characters', () => {
    expect(isValidTargetName('user_portal')).toBe(false);
    expect(isValidTargetName('user.portal')).toBe(false);
    expect(isValidTargetName('user@portal')).toBe(false);
  });

  it('should reject empty string', () => {
    expect(isValidTargetName('')).toBe(false);
  });
});

// =============================================================================
// normalizeTargetName Tests
// =============================================================================

describe('normalizeTargetName', () => {
  it('should convert to lowercase', () => {
    expect(normalizeTargetName('UserPortal')).toBe('userportal');
    expect(normalizeTargetName('UPPERCASE')).toBe('uppercase');
  });

  it('should replace special characters with hyphens', () => {
    expect(normalizeTargetName('user_portal')).toBe('user-portal');
    expect(normalizeTargetName('user.portal')).toBe('user-portal');
    expect(normalizeTargetName('user@portal')).toBe('user-portal');
  });

  it('should remove leading and trailing hyphens', () => {
    expect(normalizeTargetName('-app')).toBe('app');
    expect(normalizeTargetName('app-')).toBe('app');
    expect(normalizeTargetName('-app-')).toBe('app');
  });

  it('should collapse multiple hyphens', () => {
    expect(normalizeTargetName('user--portal')).toBe('user-portal');
    expect(normalizeTargetName('user---portal')).toBe('user-portal');
  });

  it('should return app for empty result', () => {
    expect(normalizeTargetName('')).toBe('app');
    expect(normalizeTargetName('---')).toBe('app');
    expect(normalizeTargetName('@@@')).toBe('app');
  });
});

// =============================================================================
// generateEnvironmentUrls Tests
// =============================================================================

describe('generateEnvironmentUrls', () => {
  it('should generate URLs from localhost', () => {
    const urls = generateEnvironmentUrls('http://localhost:3000', 'portal');

    expect(urls.local.baseUrl).toBe('http://localhost:3000');
    expect(urls.staging.baseUrl).toBe('https://staging.portal.example.com');
    expect(urls.production.baseUrl).toBe('https://portal.example.com');
  });

  it('should handle 127.0.0.1', () => {
    const urls = generateEnvironmentUrls('http://127.0.0.1:3000', 'app');

    expect(urls.local.baseUrl).toBe('http://127.0.0.1:3000');
    expect(urls.staging.baseUrl).toBe('https://staging.app.example.com');
  });

  it('should generate URLs from real domain', () => {
    const urls = generateEnvironmentUrls('https://app.company.com', 'portal');

    expect(urls.local.baseUrl).toBe('http://localhost:3000');
    expect(urls.staging.baseUrl).toBe('https://staging.app.company.com');
    expect(urls.production.baseUrl).toBe('https://app.company.com');
  });

  it('should strip www prefix from domain', () => {
    const urls = generateEnvironmentUrls('https://www.company.com', 'portal');

    expect(urls.production.baseUrl).toBe('https://company.com');
    expect(urls.staging.baseUrl).toBe('https://staging.company.com');
  });

  it('should strip staging prefix from domain', () => {
    const urls = generateEnvironmentUrls('https://staging.company.com', 'portal');

    expect(urls.production.baseUrl).toBe('https://company.com');
  });

  it('should use port from URL for local', () => {
    const urls = generateEnvironmentUrls('https://app.company.com:8080', 'portal');

    expect(urls.local.baseUrl).toBe('http://localhost:8080');
  });

  it('should default to port 3000', () => {
    const urls = generateEnvironmentUrls('https://app.company.com', 'portal');

    expect(urls.local.baseUrl).toBe('http://localhost:3000');
  });
});

// =============================================================================
// generateArtkConfigWithResult Tests
// =============================================================================

describe('generateArtkConfigWithResult', () => {
  it('should return result with content', () => {
    const result = generateArtkConfigWithResult(createMockOptions());

    expect(result.content).toContain('project:');
    expect(result.content).toContain('targets:');
  });

  it('should return target count', () => {
    const result = generateArtkConfigWithResult(
      createMockOptions({
        targets: [
          {
            name: 'a',
            path: './a',
            type: 'react-spa',
            environments: { local: { baseUrl: 'http://localhost:3000' } },
          },
          {
            name: 'b',
            path: './b',
            type: 'react-spa',
            environments: { local: { baseUrl: 'http://localhost:3001' } },
          },
        ],
      })
    );

    expect(result.targetCount).toBe(2);
  });

  it('should return default target', () => {
    const result = generateArtkConfigWithResult(
      createMockOptions({ defaultTarget: 'user-portal' })
    );

    expect(result.defaultTarget).toBe('user-portal');
  });

  it('should use first target as default when not specified', () => {
    const result = generateArtkConfigWithResult(createMockOptions());

    expect(result.defaultTarget).toBe('user-portal');
  });

  it('should return target names', () => {
    const result = generateArtkConfigWithResult(
      createMockOptions({
        targets: [
          {
            name: 'frontend',
            path: './frontend',
            type: 'react-spa',
            environments: { local: { baseUrl: 'http://localhost:3000' } },
          },
          {
            name: 'admin',
            path: './admin',
            type: 'react-spa',
            environments: { local: { baseUrl: 'http://localhost:3001' } },
          },
        ],
      })
    );

    expect(result.targetNames).toEqual(['frontend', 'admin']);
  });

  it('should warn about invalid target names', () => {
    const result = generateArtkConfigWithResult(
      createMockOptions({
        targets: [
          {
            name: 'UserPortal', // Invalid - should be lowercase
            path: './src',
            type: 'react-spa',
            environments: { local: { baseUrl: 'http://localhost:3000' } },
          },
        ],
      })
    );

    expect(result.warnings.length).toBeGreaterThan(0);
    expect(result.warnings[0]).toContain('normalized');
    expect(result.targetNames).toEqual(['userportal']);
  });

  it('should warn about duplicate target names', () => {
    const result = generateArtkConfigWithResult(
      createMockOptions({
        targets: [
          {
            name: 'app',
            path: './app1',
            type: 'react-spa',
            environments: { local: { baseUrl: 'http://localhost:3000' } },
          },
          {
            name: 'app',
            path: './app2',
            type: 'react-spa',
            environments: { local: { baseUrl: 'http://localhost:3001' } },
          },
        ],
      })
    );

    expect(result.warnings.some((w) => w.includes('Duplicate'))).toBe(true);
  });

  it('should warn about target count exceeding limit', () => {
    const targets: ConfigTargetInput[] = [];
    for (let i = 0; i < 6; i++) {
      targets.push({
        name: `target${i}`,
        path: `./target${i}`,
        type: 'react-spa',
        environments: { local: { baseUrl: `http://localhost:300${i}` } },
      });
    }

    const result = generateArtkConfigWithResult(
      createMockOptions({ targets })
    );

    expect(result.warnings.some((w) => w.includes('exceeds recommended limit'))).toBe(
      true
    );
  });

  it('should return empty warnings for valid config', () => {
    const result = generateArtkConfigWithResult(createMockOptions());

    expect(result.warnings).toEqual([]);
  });
});
