/**
 * Version utilities for generated code branding
 */
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Get the package version from package.json
 */
export function getPackageVersion(): string {
  try {
    // Try multiple paths to find package.json (works in both src and dist)
    const paths = [
      join(__dirname, '..', '..', 'package.json'),  // from src/utils/
      join(__dirname, '..', 'package.json'),         // from dist/utils/
    ];

    for (const pkgPath of paths) {
      try {
        const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
        if (pkg.version) {
          return pkg.version;
        }
      } catch {
        // Try next path
      }
    }
    return 'unknown';
  } catch {
    return 'unknown';
  }
}

/**
 * Get ISO timestamp for generated file headers
 */
export function getGeneratedTimestamp(): string {
  return new Date().toISOString();
}

/**
 * Generate a standard header comment for generated files
 */
export interface GeneratedHeaderOptions {
  title?: string;
  journeyId?: string;
  tags?: string[];
  tier?: string;
  scope?: string;
  actor?: string;
}

export function generateFileHeader(options: GeneratedHeaderOptions = {}): string {
  const version = getPackageVersion();
  const timestamp = getGeneratedTimestamp();

  const lines = [
    '/**',
    options.title ? ` * ${options.title}` : ' * Generated file',
    options.journeyId ? ` * Journey: ${options.journeyId}` : null,
    ` *`,
    ` * @generated by @artk/core-autogen v${version}`,
    ` * @timestamp ${timestamp}`,
    ` * @warning DO NOT EDIT - Changes will be overwritten on regeneration`,
  ];

  if (options.tags && options.tags.length > 0) {
    lines.push(` * @tags ${options.tags.join(', ')}`);
  }
  if (options.tier) {
    lines.push(` * @tier ${options.tier}`);
  }
  if (options.scope) {
    lines.push(` * @scope ${options.scope}`);
  }
  if (options.actor) {
    lines.push(` * @actor ${options.actor}`);
  }

  lines.push(' */');

  return lines.filter(l => l !== null).join('\n');
}

/**
 * Branding string for inline comments
 */
export function getBrandingComment(): string {
  const version = getPackageVersion();
  return `@artk/core-autogen v${version}`;
}
