/**
 * Authentication Module
 * Scope: authentication
 * Generated by @artk/core-autogen
 */
import type { Page, Locator } from '@playwright/test';
import { expect } from '@playwright/test';

/**
 * Authentication - Page object for authentication functionality
 */
export class AuthenticationPage {
  readonly page: Page;


  constructor(page: Page) {
    this.page = page;

  }

}

/**
 * Factory function to create Authentication instance
 */
export function createAuthenticationPage(page: Page): AuthenticationPage {
  return new AuthenticationPage(page);
}
