/**
 * Shopping Module
 * Scope: shopping
 * Generated by @artk/core-autogen
 */
import type { Page, Locator } from '@playwright/test';
import { expect } from '@playwright/test';

/**
 * Shopping - Page object for shopping functionality
 */
export class ShoppingPage {
  readonly page: Page;


  constructor(page: Page) {
    this.page = page;

  }

}

/**
 * Factory function to create Shopping instance
 */
export function createShoppingPage(page: Page): ShoppingPage {
  return new ShoppingPage(page);
}
