/**
 * @module install/playwright-config-generator
 * @description Playwright configuration generator for ARTK E2E.
 *
 * Generates playwright.config.ts with multi-target support and
 * environment-aware configuration.
 *
 * @example
 * ```typescript
 * import { generatePlaywrightConfig, PlaywrightConfigOptions } from '@artk/core/install';
 *
 * const config = generatePlaywrightConfig({
 *   targets: ['user-portal', 'admin-portal'],
 *   defaultTarget: 'user-portal',
 * });
 *
 * await fs.writeFile('artk-e2e/playwright.config.ts', config);
 * ```
 */

/**
 * Target configuration for Playwright.
 */
export interface PlaywrightTargetConfig {
  /**
   * Target name (e.g., 'user-portal').
   */
  name: string;

  /**
   * Base URL for the target.
   * Can include environment placeholder: ${ARTK_ENV}
   */
  baseUrl?: string;

  /**
   * Test directory for this target.
   * @default `tests/${name}`
   */
  testDir?: string;

  /**
   * Storage state path for this target.
   */
  storageState?: string;
}

/**
 * Options for generating playwright.config.ts.
 */
export interface PlaywrightConfigOptions {
  /**
   * Target configurations.
   */
  targets?: PlaywrightTargetConfig[];

  /**
   * Default target name.
   */
  defaultTarget?: string;

  /**
   * Test directory (when not using targets).
   * @default 'tests'
   */
  testDir?: string;

  /**
   * Output directory for test artifacts.
   * @default 'test-results'
   */
  outputDir?: string;

  /**
   * Number of retries for failed tests.
   * @default 2
   */
  retries?: number;

  /**
   * Whether to run tests in parallel.
   * @default true
   */
  fullyParallel?: boolean;

  /**
   * Number of workers (parallel processes).
   */
  workers?: number;

  /**
   * Whether to forbid test.only() in CI.
   * @default true in CI
   */
  forbidOnly?: boolean;

  /**
   * Test timeout in milliseconds.
   * @default 30000
   */
  timeout?: number;

  /**
   * Expect (assertion) timeout in milliseconds.
   * @default 5000
   */
  expectTimeout?: number;

  /**
   * Whether to record trace on first retry.
   * @default 'on-first-retry'
   */
  trace?: 'on' | 'off' | 'on-first-retry' | 'retain-on-failure';

  /**
   * Whether to capture screenshots on failure.
   * @default 'only-on-failure'
   */
  screenshot?: 'on' | 'off' | 'only-on-failure';

  /**
   * Whether to record video on failure.
   * @default 'on-first-retry'
   */
  video?: 'on' | 'off' | 'on-first-retry' | 'retain-on-failure';

  /**
   * Browser viewport size.
   */
  viewport?: {
    width: number;
    height: number;
  };

  /**
   * Whether to run in headless mode.
   * @default true in CI
   */
  headless?: boolean;

  /**
   * Browsers to test against.
   * @default ['chromium']
   */
  browsers?: ('chromium' | 'firefox' | 'webkit')[];

  /**
   * Whether to include the reporter configuration.
   * @default true
   */
  includeReporter?: boolean;

  /**
   * Custom reporter configuration.
   */
  reporter?: string;

  /**
   * Whether to use the @artk/core harness.
   * @default true
   */
  useArtkHarness?: boolean;

  /**
   * Whether to include auth setup project.
   * @default true
   */
  includeAuthSetup?: boolean;
}

/**
 * Default options for Playwright config generation.
 */
const DEFAULT_OPTIONS: Required<Omit<PlaywrightConfigOptions, 'targets' | 'workers' | 'viewport' | 'reporter'>> & {
  targets: PlaywrightTargetConfig[];
  workers: number | undefined;
  viewport: { width: number; height: number };
  reporter: string | undefined;
} = {
  targets: [],
  defaultTarget: '',
  testDir: 'tests',
  outputDir: 'test-results',
  retries: 2,
  fullyParallel: true,
  workers: undefined,
  forbidOnly: true,
  timeout: 30000,
  expectTimeout: 5000,
  trace: 'on-first-retry',
  screenshot: 'only-on-failure',
  video: 'on-first-retry',
  viewport: { width: 1280, height: 720 },
  headless: true,
  browsers: ['chromium'],
  includeReporter: true,
  reporter: undefined,
  useArtkHarness: true,
  includeAuthSetup: true,
};

/**
 * Generates a playwright.config.ts string.
 *
 * @param options - Configuration options
 * @returns TypeScript configuration file content
 */
export function generatePlaywrightConfig(
  options?: PlaywrightConfigOptions
): string {
  const opts = {
    ...DEFAULT_OPTIONS,
    ...options,
  };

  const lines: string[] = [];

  // Header
  lines.push(`/**`);
  lines.push(` * Playwright Configuration`);
  lines.push(` * Generated by ARTK E2E`);
  lines.push(` * @see https://playwright.dev/docs/test-configuration`);
  lines.push(` */`);
  lines.push('');

  // Imports
  lines.push(`import { defineConfig, devices } from '@playwright/test';`);
  if (opts.useArtkHarness) {
    lines.push(`import { loadArtkConfig } from '@artk/core/config';`);
    lines.push(`import { validateBrowserChannel } from '@artk/core/harness';`);
  }
  lines.push('');

  // Environment variable handling
  lines.push(`// Load environment`);
  lines.push(`const env = process.env.ARTK_ENV || 'local';`);
  lines.push(`const isCI = !!process.env.CI;`);
  lines.push('');

  // ARTK config loading
  if (opts.useArtkHarness) {
    lines.push(`// Load ARTK configuration`);
    lines.push(`const artkConfig = loadArtkConfig();`);
    lines.push('');
  }

  // Export config
  lines.push(`export default defineConfig({`);

  // Test directory
  lines.push(`  testDir: '${opts.testDir}',`);

  // Output
  lines.push(`  outputDir: '${opts.outputDir}',`);

  // Parallel execution
  lines.push(`  fullyParallel: ${opts.fullyParallel},`);

  // Forbid only in CI
  lines.push(`  forbidOnly: isCI,`);

  // Retries
  lines.push(`  retries: isCI ? ${opts.retries} : 0,`);

  // Workers
  if (opts.workers !== undefined) {
    lines.push(`  workers: ${opts.workers},`);
  } else {
    lines.push(`  workers: isCI ? 1 : undefined,`);
  }

  // Timeouts
  lines.push(`  timeout: ${opts.timeout},`);
  lines.push(`  expect: {`);
  lines.push(`    timeout: ${opts.expectTimeout},`);
  lines.push(`  },`);

  if (opts.useArtkHarness) {
    lines.push('');
    lines.push(`  // Global setup: validate browser availability`);
    lines.push(`  async globalSetup() {`);
    lines.push(`    const config = loadArtkConfig();`);
    lines.push(`    if (config.browsers.channel && config.browsers.channel !== 'bundled') {`);
    lines.push(`      const validation = await validateBrowserChannel(config.browsers.channel);`);
    lines.push(`      if (!validation.available) {`);
    lines.push(`        console.error('\\nBrowser validation failed:\\n');`);
    lines.push(`        console.error(\`  Configured: \${config.browsers.channel}\`);`);
    lines.push(`        console.error('  Status: Not available');`);
    lines.push(`        console.error(\`  Reason: \${validation.reason}\\n\`);`);
    lines.push(`        console.error('Solutions:');`);
    lines.push(`        console.error('  1. Install the browser (see reason above)');`);
    lines.push(`        console.error(\`  2. Edit artk.config.yml and remove or change 'channel'\`);`);
    lines.push(`        console.error('  3. Run bootstrap again to auto-detect browsers\\n');`);
    lines.push(`        throw new Error(\`Browser \${config.browsers.channel} not available\`);`);
    lines.push(`      }`);
    lines.push(`      console.log(\`Browser validated: \${config.browsers.channel} v\${validation.version}\`);`);
    lines.push(`    }`);
    lines.push(`  },`);
  }

  // Reporter
  if (opts.includeReporter) {
    lines.push(`  reporter: isCI ? 'github' : [['html', { open: 'never' }]],`);
  } else if (opts.reporter) {
    lines.push(`  reporter: ${opts.reporter},`);
  }

  // Use (shared test settings)
  lines.push(`  use: {`);
  lines.push(`    // Base URL - defaults to first target or env variable`);
  if (opts.useArtkHarness && opts.targets.length > 0) {
    const defaultTarget = opts.defaultTarget || opts.targets[0]?.name;
    lines.push(`    baseURL: artkConfig.getTargetUrl('${defaultTarget}', env),`);
  } else {
    lines.push(`    baseURL: process.env.BASE_URL || 'http://localhost:3000',`);
  }
  lines.push('');
  lines.push(`    // Tracing and screenshots`);
  lines.push(`    trace: '${opts.trace}',`);
  lines.push(`    screenshot: '${opts.screenshot}',`);
  lines.push(`    video: '${opts.video}',`);
  lines.push('');
  lines.push(`    // Viewport`);
  lines.push(`    viewport: { width: ${opts.viewport.width}, height: ${opts.viewport.height} },`);
  lines.push('');
  lines.push(`    // Headless mode`);
  lines.push(`    headless: isCI || ${opts.headless},`);
  lines.push(`  },`);

  // Projects (browsers and targets)
  lines.push('');
  lines.push(`  projects: [`);

  // Auth setup project
  if (opts.includeAuthSetup) {
    lines.push(`    // Authentication setup`);
    lines.push(`    {`);
    lines.push(`      name: 'setup',`);
    lines.push(`      testMatch: /.*\\.setup\\.ts/,`);
    lines.push(`    },`);
    lines.push('');
  }

  // Browser projects
  for (const browser of opts.browsers) {
    const deviceName = getDeviceName(browser);
    const dependencies = opts.includeAuthSetup ? `['setup']` : '[]';

    lines.push(`    {`);
    lines.push(`      name: '${browser}',`);
    lines.push(`      use: { ...devices['${deviceName}'] },`);
    lines.push(`      dependencies: ${dependencies},`);
    lines.push(`    },`);
  }

  // Target-specific projects
  if (opts.targets.length > 0) {
    lines.push('');
    lines.push(`    // Target-specific projects`);
    for (const target of opts.targets) {
      lines.push(`    {`);
      lines.push(`      name: '${target.name}',`);
      lines.push(`      testDir: '${target.testDir || `tests/${target.name}`}',`);
      if (opts.useArtkHarness) {
        lines.push(`      use: {`);
        lines.push(`        baseURL: artkConfig.getTargetUrl('${target.name}', env),`);
        if (target.storageState) {
          lines.push(`        storageState: '${target.storageState}',`);
        }
        lines.push(`      },`);
      }
      lines.push(`      dependencies: ['setup'],`);
      lines.push(`    },`);
    }
  }

  lines.push(`  ],`);

  // Web server (optional)
  lines.push('');
  lines.push(`  // Uncomment to start your dev server before tests`);
  lines.push(`  // webServer: {`);
  lines.push(`  //   command: 'npm run dev',`);
  lines.push(`  //   url: 'http://localhost:3000',`);
  lines.push(`  //   reuseExistingServer: !isCI,`);
  lines.push(`  // },`);

  lines.push(`});`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Gets the Playwright device name for a browser.
 */
function getDeviceName(browser: 'chromium' | 'firefox' | 'webkit'): string {
  switch (browser) {
    case 'chromium':
      return 'Desktop Chrome';
    case 'firefox':
      return 'Desktop Firefox';
    case 'webkit':
      return 'Desktop Safari';
  }
}

/**
 * Generates a minimal playwright.config.ts for quick setup.
 */
export function generateMinimalPlaywrightConfig(): string {
  return `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: process.env.BASE_URL || 'http://localhost:3000',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
`;
}

/**
 * Generates tsconfig.json for the E2E test project.
 */
export function generateTsConfig(): string {
  const config = {
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'bundler',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      declaration: false,
      noEmit: true,
      paths: {
        '@artk/core/*': ['./vendor/artk-core/*'],
      },
    },
    include: ['tests/**/*.ts', 'playwright.config.ts'],
    exclude: ['node_modules'],
  };

  return JSON.stringify(config, null, 2) + '\n';
}
