/**
 * User Login
 * Journey: JRN-0001
 * Generated by @artk/core-autogen
 *
 * @tags @artk, @journey, @JRN-0001, @tier-smoke, @scope-authentication, @actor-registered_user
 * @tier smoke
 * @scope authentication
 * @actor registered_user
 */
import { test, expect } from '@playwright/test';


test.describe('User Login', {
  tag: ['@artk', '@journey', '@JRN-0001', '@tier-smoke', '@scope-authentication', '@actor-registered_user'],
}, () => {

  test('JRN-0001: User Login', async ({ page }) => {


    // Verify completion signals
    await test.step('Verify completion', async () => {



      await expect(page).toHaveURL(//dashboard/);


    });

  });

});
