/**
 * Add Product to Cart
 * Journey: JRN-0002
 * Generated by @artk/core-autogen
 *
 * @tags @artk, @journey, @JRN-0002, @tier-smoke, @scope-shopping, @actor-guest_user
 * @tier smoke
 * @scope shopping
 * @actor guest_user
 */
import { test, expect } from '@playwright/test';


test.describe('Add Product to Cart', {
  tag: ['@artk', '@journey', '@JRN-0002', '@tier-smoke', '@scope-shopping', '@actor-guest_user'],
}, () => {

  test('JRN-0002: Add Product to Cart', async ({ page }) => {


    // Verify completion signals
    await test.step('Verify completion', async () => {



      await expect(page.locator('[data-testid=\&#34;cart-badge\&#34;]')).toBeVisible();


    });

  });

});
