/**
 * @module targets/config-generator
 * @description ARTK configuration file generator for multi-target architecture.
 *
 * Generates artk.config.yml files with target definitions and environment URLs.
 *
 * @example
 * ```typescript
 * import { generateArtkConfig, ConfigGeneratorOptions } from '@artk/core/targets';
 *
 * const config = generateArtkConfig({
 *   projectName: 'my-project',
 *   targets: [
 *     {
 *       name: 'user-portal',
 *       path: '../frontend',
 *       type: 'react-spa',
 *       environments: {
 *         local: { baseUrl: 'http://localhost:3000' },
 *         staging: { baseUrl: 'https://staging.example.com' },
 *       },
 *     },
 *   ],
 * });
 *
 * await fs.writeFile('artk-e2e/artk.config.yml', config);
 * ```
 */

import type { ArtkEnvironmentUrls } from '../types/config.js';
import type { ArtkTargetType } from '../types/target.js';

/**
 * Target input for config generation.
 */
export interface ConfigTargetInput {
  /**
   * Target name (lowercase-kebab-case).
   */
  name: string;

  /**
   * Relative path from artk-e2e/ to frontend directory.
   */
  path: string;

  /**
   * Application type.
   */
  type: ArtkTargetType;

  /**
   * Optional description.
   */
  description?: string;

  /**
   * Environment URLs.
   */
  environments: Record<string, ArtkEnvironmentUrls>;
}

/**
 * Options for generating artk.config.yml.
 */
export interface ConfigGeneratorOptions {
  /**
   * Project name.
   */
  projectName: string;

  /**
   * Optional project description.
   */
  projectDescription?: string;

  /**
   * Target configurations.
   */
  targets: ConfigTargetInput[];

  /**
   * Default target name.
   * If not specified, uses the first target.
   */
  defaultTarget?: string;

  /**
   * Default environment name.
   * @default 'local'
   */
  defaultEnvironment?: string;

  /**
   * Whether to include auth configuration section.
   * @default false
   */
  includeAuth?: boolean;

  /**
   * Storage state directory for auth.
   * @default '.auth-states'
   */
  storageStateDir?: string;

  /**
   * Whether to include browser configuration.
   * @default true
   */
  includeBrowserConfig?: boolean;

  /**
   * Enabled browsers.
   * @default ['chromium']
   */
  browsers?: ('chromium' | 'firefox' | 'webkit')[];

  /**
   * Whether to include timeout configuration.
   * @default true
   */
  includeTimeouts?: boolean;

  /**
   * Whether to include comments in output.
   * @default true
   */
  includeComments?: boolean;
}

/**
 * Default configuration options.
 */
const DEFAULT_OPTIONS: Partial<ConfigGeneratorOptions> = {
  defaultEnvironment: 'local',
  includeAuth: false,
  storageStateDir: '.auth-states',
  includeBrowserConfig: true,
  browsers: ['chromium'],
  includeTimeouts: true,
  includeComments: true,
};

/**
 * Generates YAML content for artk.config.yml.
 *
 * @param options - Configuration options
 * @returns YAML configuration file content
 */
export function generateArtkConfig(options: ConfigGeneratorOptions): string {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const lines: string[] = [];

  // Header
  if (opts.includeComments) {
    lines.push('# ARTK E2E Configuration');
    lines.push('# Generated by ARTK init');
    lines.push('# See: https://artk.dev/docs/config');
    lines.push('');
  }

  // Schema version
  lines.push('schemaVersion: "2.0"');
  lines.push('');

  // Project section
  if (opts.includeComments) {
    lines.push('# Project metadata');
  }
  lines.push('project:');
  lines.push(`  name: ${opts.projectName}`);
  if (opts.projectDescription) {
    lines.push(`  description: ${quoteIfNeeded(opts.projectDescription)}`);
  }
  lines.push('');

  // Targets section
  if (opts.includeComments) {
    lines.push('# Frontend targets to test');
  }
  lines.push('targets:');
  for (const target of opts.targets) {
    lines.push(`  - name: ${target.name}`);
    lines.push(`    path: ${target.path}`);
    lines.push(`    type: ${target.type}`);
    if (target.description) {
      lines.push(`    description: ${quoteIfNeeded(target.description)}`);
    }
    lines.push('    environments:');
    for (const [envName, envConfig] of Object.entries(target.environments)) {
      lines.push(`      ${envName}:`);
      lines.push(`        baseUrl: ${envConfig.baseUrl}`);
      if (envConfig.apiUrl) {
        lines.push(`        apiUrl: ${envConfig.apiUrl}`);
      }
    }
  }
  lines.push('');

  // Defaults section
  if (opts.includeComments) {
    lines.push('# Default settings');
  }
  lines.push('defaults:');
  lines.push(`  target: ${opts.defaultTarget || opts.targets[0]?.name || 'default'}`);
  lines.push(`  environment: ${opts.defaultEnvironment}`);
  lines.push('');

  // Auth section (optional)
  if (opts.includeAuth) {
    if (opts.includeComments) {
      lines.push('# Authentication configuration');
    }
    lines.push('auth:');
    lines.push('  enabled: true');
    lines.push(`  storageStateDir: ${opts.storageStateDir}`);
    lines.push('  roles:');
    lines.push('    default:');
    lines.push('      credentialsEnv:');
    lines.push('        username: ARTK_USERNAME');
    lines.push('        password: ARTK_PASSWORD');
    if (opts.includeComments) {
      lines.push('  # Uncomment for OIDC authentication:');
      lines.push('  # oidc:');
      lines.push('  #   idpType: keycloak');
      lines.push('  #   loginUrl: /auth/login');
      lines.push('  #   success:');
      lines.push('  #     url: /dashboard');
    }
    lines.push('');
  }

  // Browser configuration (optional)
  if (opts.includeBrowserConfig) {
    if (opts.includeComments) {
      lines.push('# Browser configuration');
    }
    lines.push('browsers:');
    lines.push('  enabled:');
    for (const browser of opts.browsers || ['chromium']) {
      lines.push(`    - ${browser}`);
    }
    lines.push('  headless: true');
    lines.push('');
  }

  // Timeout configuration (optional)
  if (opts.includeTimeouts) {
    if (opts.includeComments) {
      lines.push('# Timeout configuration (milliseconds)');
    }
    lines.push('timeouts:');
    lines.push('  default: 30000');
    lines.push('  navigation: 60000');
    lines.push('  auth: 120000');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generates a minimal artk.config.yml for quick setup.
 *
 * @param projectName - Project name
 * @param targetPath - Path to the frontend directory
 * @param targetType - Application type
 * @returns Minimal YAML configuration
 */
export function generateMinimalArtkConfig(
  projectName: string,
  targetPath: string,
  targetType: ArtkTargetType = 'react-spa'
): string {
  return generateArtkConfig({
    projectName,
    targets: [
      {
        name: 'main',
        path: targetPath,
        type: targetType,
        environments: {
          local: { baseUrl: 'http://localhost:3000' },
        },
      },
    ],
    includeAuth: false,
    includeBrowserConfig: false,
    includeTimeouts: false,
    includeComments: false,
  });
}

/**
 * Generates artk.config.yml from detected targets.
 *
 * @param projectName - Project name
 * @param detectedTargets - Targets detected by frontend detector
 * @returns YAML configuration
 */
export function generateConfigFromDetection(
  projectName: string,
  detectedTargets: Array<{
    name: string;
    path: string;
    type: ArtkTargetType;
    description?: string;
  }>
): string {
  const targets: ConfigTargetInput[] = detectedTargets.map((target) => ({
    name: target.name,
    path: target.path,
    type: target.type,
    description: target.description,
    environments: {
      local: {
        baseUrl: 'http://localhost:3000',
      },
      staging: {
        baseUrl: `https://staging.${target.name}.example.com`,
      },
      production: {
        baseUrl: `https://${target.name}.example.com`,
      },
    },
  }));

  return generateArtkConfig({
    projectName,
    targets,
    includeAuth: true,
    includeComments: true,
  });
}

/**
 * Validates a target name follows the lowercase-kebab-case pattern.
 */
export function isValidTargetName(name: string): boolean {
  return /^[a-z][a-z0-9-]*$/.test(name);
}

/**
 * Normalizes a directory name to a valid target name.
 *
 * @param dirName - Directory name to normalize
 * @returns Valid target name
 */
export function normalizeTargetName(dirName: string): string {
  return dirName
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-+/g, '-')
    || 'app';
}

/**
 * Quotes a string if it contains special YAML characters.
 */
function quoteIfNeeded(value: string): string {
  // Check for special characters that need quoting
  if (/[:#{}[\],&*?|<>=!%@`]/.test(value) || value.includes('\n')) {
    return `"${value.replace(/"/g, '\\"')}"`;
  }
  return value;
}

/**
 * Parses environment URLs from common patterns.
 *
 * @param baseUrl - Base URL for local environment
 * @param targetName - Target name for generating other URLs
 * @returns Environment URLs map
 */
export function generateEnvironmentUrls(
  baseUrl: string,
  targetName: string
): Record<string, ArtkEnvironmentUrls> {
  // Extract domain from base URL for staging/production generation
  const url = new URL(baseUrl);
  const isLocalhost = url.hostname === 'localhost' || url.hostname === '127.0.0.1';

  if (isLocalhost) {
    return {
      local: { baseUrl },
      staging: {
        baseUrl: `https://staging.${targetName}.example.com`,
      },
      production: {
        baseUrl: `https://${targetName}.example.com`,
      },
    };
  }

  // If not localhost, assume it's already a real URL
  const domain = url.hostname.replace(/^(www|staging|dev)\./, '');
  return {
    local: {
      baseUrl: `http://localhost:${url.port || '3000'}`,
    },
    staging: {
      baseUrl: `https://staging.${domain}`,
    },
    production: {
      baseUrl: `https://${domain}`,
    },
  };
}

/**
 * Config generator result with metadata.
 */
export interface ConfigGeneratorResult {
  /**
   * Generated YAML content.
   */
  content: string;

  /**
   * Number of targets in config.
   */
  targetCount: number;

  /**
   * Default target name.
   */
  defaultTarget: string;

  /**
   * List of all target names.
   */
  targetNames: string[];

  /**
   * Warnings from generation (e.g., normalized target names).
   */
  warnings: string[];
}

/**
 * Generates artk.config.yml with detailed result.
 *
 * @param options - Configuration options
 * @returns Generation result with metadata
 */
export function generateArtkConfigWithResult(
  options: ConfigGeneratorOptions
): ConfigGeneratorResult {
  const warnings: string[] = [];

  // Validate and normalize target names
  const normalizedTargets = options.targets.map((target) => {
    if (!isValidTargetName(target.name)) {
      const normalized = normalizeTargetName(target.name);
      warnings.push(
        `Target name "${target.name}" normalized to "${normalized}"`
      );
      return { ...target, name: normalized };
    }
    return target;
  });

  // Check for duplicate target names
  const names = normalizedTargets.map((t) => t.name);
  const duplicates = names.filter((name, i) => names.indexOf(name) !== i);
  if (duplicates.length > 0) {
    warnings.push(`Duplicate target names detected: ${duplicates.join(', ')}`);
  }

  // Check target count limit
  if (normalizedTargets.length > 5) {
    warnings.push(
      `Target count (${normalizedTargets.length}) exceeds recommended limit of 5`
    );
  }

  const content = generateArtkConfig({
    ...options,
    targets: normalizedTargets,
  });

  const defaultTarget =
    options.defaultTarget || normalizedTargets[0]?.name || 'default';

  return {
    content,
    targetCount: normalizedTargets.length,
    defaultTarget,
    targetNames: normalizedTargets.map((t) => t.name),
    warnings,
  };
}
