/**
 * Unit tests for Playwright config generator
 *
 * @group unit
 * @group install
 */

import { describe, expect, it } from 'vitest';
import {
  generatePlaywrightConfig,
  generateMinimalPlaywrightConfig,
  generateTsConfig,
  type PlaywrightConfigOptions,
  type PlaywrightTargetConfig,
} from '../playwright-config-generator.js';

// =============================================================================
// generatePlaywrightConfig Tests
// =============================================================================

describe('generatePlaywrightConfig', () => {
  describe('basic structure', () => {
    it('should generate valid TypeScript config', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain("import { defineConfig, devices } from '@playwright/test'");
      expect(config).toContain('export default defineConfig({');
      expect(config).toContain('});');
    });

    it('should include header comment', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain('/**');
      expect(config).toContain('* Playwright Configuration');
      expect(config).toContain('* Generated by ARTK E2E');
      expect(config).toContain('@see https://playwright.dev/docs/test-configuration');
    });

    it('should include environment variable handling', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain("const env = process.env.ARTK_ENV || 'local'");
      expect(config).toContain('const isCI = !!process.env.CI');
    });
  });

  describe('default options', () => {
    it('should use default testDir', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain("testDir: 'tests'");
    });

    it('should use default outputDir', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain("outputDir: 'test-results'");
    });

    it('should enable fullyParallel by default', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain('fullyParallel: true');
    });

    it('should set retries to 2 in CI', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain('retries: isCI ? 2 : 0');
    });

    it('should use default timeout values', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain('timeout: 30000');
      expect(config).toContain('timeout: 5000'); // expect timeout
    });

    it('should use default trace setting', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain("trace: 'on-first-retry'");
    });

    it('should use default screenshot setting', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain("screenshot: 'only-on-failure'");
    });

    it('should use default video setting', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain("video: 'on-first-retry'");
    });

    it('should use default viewport', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain('viewport: { width: 1280, height: 720 }');
    });

    it('should include chromium browser by default', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain("name: 'chromium'");
      expect(config).toContain("devices['Desktop Chrome']");
    });
  });

  describe('custom options', () => {
    it('should use custom testDir', () => {
      const config = generatePlaywrightConfig({ testDir: 'e2e' });

      expect(config).toContain("testDir: 'e2e'");
    });

    it('should use custom outputDir', () => {
      const config = generatePlaywrightConfig({ outputDir: 'results' });

      expect(config).toContain("outputDir: 'results'");
    });

    it('should use custom retries', () => {
      const config = generatePlaywrightConfig({ retries: 5 });

      expect(config).toContain('retries: isCI ? 5 : 0');
    });

    it('should use custom timeout', () => {
      const config = generatePlaywrightConfig({ timeout: 60000 });

      expect(config).toContain('timeout: 60000');
    });

    it('should use custom expectTimeout', () => {
      const config = generatePlaywrightConfig({ expectTimeout: 10000 });

      expect(config).toContain('timeout: 10000');
    });

    it('should use specified workers count', () => {
      const config = generatePlaywrightConfig({ workers: 4 });

      expect(config).toContain('workers: 4');
      expect(config).not.toContain('workers: isCI ? 1 : undefined');
    });

    it('should use default workers when not specified', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain('workers: isCI ? 1 : undefined');
    });

    it('should use custom viewport', () => {
      const config = generatePlaywrightConfig({
        viewport: { width: 1920, height: 1080 },
      });

      expect(config).toContain('viewport: { width: 1920, height: 1080 }');
    });

    it('should use custom trace setting', () => {
      const config = generatePlaywrightConfig({ trace: 'on' });

      expect(config).toContain("trace: 'on'");
    });

    it('should use custom screenshot setting', () => {
      const config = generatePlaywrightConfig({ screenshot: 'on' });

      expect(config).toContain("screenshot: 'on'");
    });

    it('should use custom video setting', () => {
      const config = generatePlaywrightConfig({ video: 'retain-on-failure' });

      expect(config).toContain("video: 'retain-on-failure'");
    });
  });

  describe('ARTK harness integration', () => {
    it('should import loadArtkConfig when useArtkHarness is true', () => {
      const config = generatePlaywrightConfig({ useArtkHarness: true });

      expect(config).toContain("import { loadArtkConfig } from '@artk/core/config'");
      expect(config).toContain('const artkConfig = loadArtkConfig()');
    });

    it('should not import loadArtkConfig when useArtkHarness is false', () => {
      const config = generatePlaywrightConfig({ useArtkHarness: false });

      expect(config).not.toContain("import { loadArtkConfig } from '@artk/core/config'");
      expect(config).not.toContain('const artkConfig = loadArtkConfig()');
    });

    it('should use artkConfig.getTargetUrl when harness enabled with targets', () => {
      const targets: PlaywrightTargetConfig[] = [
        { name: 'user-portal' },
        { name: 'admin-portal' },
      ];
      const config = generatePlaywrightConfig({
        useArtkHarness: true,
        targets,
      });

      expect(config).toContain("artkConfig.getTargetUrl('user-portal', env)");
    });

    it('should use process.env.BASE_URL when harness disabled', () => {
      const config = generatePlaywrightConfig({ useArtkHarness: false });

      expect(config).toContain("process.env.BASE_URL || 'http://localhost:3000'");
    });
  });

  describe('browser configuration', () => {
    it('should include multiple browsers', () => {
      const config = generatePlaywrightConfig({
        browsers: ['chromium', 'firefox', 'webkit'],
      });

      expect(config).toContain("name: 'chromium'");
      expect(config).toContain("devices['Desktop Chrome']");
      expect(config).toContain("name: 'firefox'");
      expect(config).toContain("devices['Desktop Firefox']");
      expect(config).toContain("name: 'webkit'");
      expect(config).toContain("devices['Desktop Safari']");
    });

    it('should include dependencies on setup when auth included', () => {
      const config = generatePlaywrightConfig({
        includeAuthSetup: true,
        browsers: ['chromium'],
      });

      expect(config).toContain("dependencies: ['setup']");
    });

    it('should have empty dependencies when auth not included', () => {
      const config = generatePlaywrightConfig({
        includeAuthSetup: false,
        browsers: ['chromium'],
      });

      expect(config).toContain('dependencies: []');
    });
  });

  describe('auth setup project', () => {
    it('should include setup project when includeAuthSetup is true', () => {
      const config = generatePlaywrightConfig({ includeAuthSetup: true });

      expect(config).toContain("name: 'setup'");
      expect(config).toContain('testMatch: /.*\\.setup\\.ts/');
    });

    it('should not include setup project when includeAuthSetup is false', () => {
      const config = generatePlaywrightConfig({ includeAuthSetup: false });

      expect(config).not.toContain("name: 'setup'");
    });
  });

  describe('targets configuration', () => {
    it('should generate target-specific projects', () => {
      const targets: PlaywrightTargetConfig[] = [
        { name: 'user-portal', testDir: 'tests/user' },
        { name: 'admin-portal', testDir: 'tests/admin' },
      ];
      const config = generatePlaywrightConfig({ targets, useArtkHarness: true });

      expect(config).toContain("name: 'user-portal'");
      expect(config).toContain("testDir: 'tests/user'");
      expect(config).toContain("name: 'admin-portal'");
      expect(config).toContain("testDir: 'tests/admin'");
    });

    it('should use default testDir for targets', () => {
      const targets: PlaywrightTargetConfig[] = [{ name: 'portal' }];
      const config = generatePlaywrightConfig({ targets, useArtkHarness: true });

      expect(config).toContain("testDir: 'tests/portal'");
    });

    it('should include storageState when specified', () => {
      const targets: PlaywrightTargetConfig[] = [
        { name: 'portal', storageState: '.auth-states/portal.json' },
      ];
      const config = generatePlaywrightConfig({ targets, useArtkHarness: true });

      expect(config).toContain("storageState: '.auth-states/portal.json'");
    });

    it('should use defaultTarget for base URL', () => {
      const targets: PlaywrightTargetConfig[] = [
        { name: 'portal-a' },
        { name: 'portal-b' },
      ];
      const config = generatePlaywrightConfig({
        targets,
        defaultTarget: 'portal-b',
        useArtkHarness: true,
      });

      expect(config).toContain("artkConfig.getTargetUrl('portal-b', env)");
    });

    it('should use first target as default when defaultTarget not specified', () => {
      const targets: PlaywrightTargetConfig[] = [
        { name: 'first-portal' },
        { name: 'second-portal' },
      ];
      const config = generatePlaywrightConfig({ targets, useArtkHarness: true });

      expect(config).toContain("artkConfig.getTargetUrl('first-portal', env)");
    });
  });

  describe('reporter configuration', () => {
    it('should include default reporter when includeReporter is true', () => {
      const config = generatePlaywrightConfig({ includeReporter: true });

      expect(config).toContain("reporter: isCI ? 'github' : [['html', { open: 'never' }]]");
    });

    it('should not include reporter when includeReporter is false and no custom reporter', () => {
      const config = generatePlaywrightConfig({
        includeReporter: false,
        reporter: undefined,
      });

      expect(config).not.toContain('reporter:');
    });

    it('should use custom reporter when specified', () => {
      const config = generatePlaywrightConfig({
        includeReporter: false,
        reporter: "'json'",
      });

      expect(config).toContain("reporter: 'json'");
    });
  });

  describe('web server comment', () => {
    it('should include commented webServer configuration', () => {
      const config = generatePlaywrightConfig();

      expect(config).toContain('// Uncomment to start your dev server before tests');
      expect(config).toContain("// webServer: {");
      expect(config).toContain("//   command: 'npm run dev'");
    });
  });
});

// =============================================================================
// generateMinimalPlaywrightConfig Tests
// =============================================================================

describe('generateMinimalPlaywrightConfig', () => {
  it('should generate minimal config', () => {
    const config = generateMinimalPlaywrightConfig();

    expect(config).toContain("import { defineConfig, devices } from '@playwright/test'");
    expect(config).toContain('export default defineConfig({');
  });

  it('should use ./tests as testDir', () => {
    const config = generateMinimalPlaywrightConfig();

    expect(config).toContain("testDir: './tests'");
  });

  it('should enable fullyParallel', () => {
    const config = generateMinimalPlaywrightConfig();

    expect(config).toContain('fullyParallel: true');
  });

  it('should forbid only in CI', () => {
    const config = generateMinimalPlaywrightConfig();

    expect(config).toContain('forbidOnly: !!process.env.CI');
  });

  it('should use CI-aware retries', () => {
    const config = generateMinimalPlaywrightConfig();

    expect(config).toContain('retries: process.env.CI ? 2 : 0');
  });

  it('should use CI-aware workers', () => {
    const config = generateMinimalPlaywrightConfig();

    expect(config).toContain('workers: process.env.CI ? 1 : undefined');
  });

  it('should use html reporter', () => {
    const config = generateMinimalPlaywrightConfig();

    expect(config).toContain("reporter: 'html'");
  });

  it('should include trace on first retry', () => {
    const config = generateMinimalPlaywrightConfig();

    expect(config).toContain("trace: 'on-first-retry'");
  });

  it('should include chromium project only', () => {
    const config = generateMinimalPlaywrightConfig();

    expect(config).toContain("name: 'chromium'");
    expect(config).toContain("devices['Desktop Chrome']");
    expect(config).not.toContain("name: 'firefox'");
    expect(config).not.toContain("name: 'webkit'");
  });

  it('should use BASE_URL environment variable', () => {
    const config = generateMinimalPlaywrightConfig();

    expect(config).toContain("process.env.BASE_URL || 'http://localhost:3000'");
  });
});

// =============================================================================
// generateTsConfig Tests
// =============================================================================

describe('generateTsConfig', () => {
  it('should generate valid JSON', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed).toHaveProperty('compilerOptions');
    expect(parsed).toHaveProperty('include');
    expect(parsed).toHaveProperty('exclude');
  });

  it('should target ES2022', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed.compilerOptions.target).toBe('ES2022');
  });

  it('should use ESNext module', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed.compilerOptions.module).toBe('ESNext');
  });

  it('should use bundler moduleResolution', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed.compilerOptions.moduleResolution).toBe('bundler');
  });

  it('should enable strict mode', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed.compilerOptions.strict).toBe(true);
  });

  it('should enable esModuleInterop', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed.compilerOptions.esModuleInterop).toBe(true);
  });

  it('should skip lib check', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed.compilerOptions.skipLibCheck).toBe(true);
  });

  it('should force consistent casing', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed.compilerOptions.forceConsistentCasingInFileNames).toBe(true);
  });

  it('should resolve JSON modules', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed.compilerOptions.resolveJsonModule).toBe(true);
  });

  it('should disable declaration', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed.compilerOptions.declaration).toBe(false);
  });

  it('should enable noEmit', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed.compilerOptions.noEmit).toBe(true);
  });

  it('should include @artk/core path alias', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed.compilerOptions.paths).toEqual({
      '@artk/core/*': ['./vendor/artk-core/*'],
    });
  });

  it('should include tests and playwright.config.ts', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed.include).toContain('tests/**/*.ts');
    expect(parsed.include).toContain('playwright.config.ts');
  });

  it('should exclude node_modules', () => {
    const tsconfig = generateTsConfig();
    const parsed = JSON.parse(tsconfig);

    expect(parsed.exclude).toContain('node_modules');
  });

  it('should end with newline', () => {
    const tsconfig = generateTsConfig();

    expect(tsconfig.endsWith('\n')).toBe(true);
  });
});
