#!/bin/bash
# Sync variant utilities from cli/ to packages/cli/
# This keeps the two CLI directories in sync automatically
#
# Source of truth: cli/src/utils/variant-*.ts
# Target: packages/cli/src/lib/variants/
#
# Run manually: ./scripts/sync-cli-variants.sh
# Runs automatically: via pre-commit hook

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

SOURCE_DIR="$ROOT_DIR/cli/src/utils"
TARGET_DIR="$ROOT_DIR/packages/cli/src/lib/variants"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if source directory exists
if [ ! -d "$SOURCE_DIR" ]; then
    echo -e "${YELLOW}⚠ cli/src/utils/ not found - skipping sync${NC}"
    exit 0
fi

# Create target directory if it doesn't exist
mkdir -p "$TARGET_DIR"

# Files to sync (variant utilities)
VARIANT_FILES=(
    "variant-definitions.ts"
    "variant-detector.ts"
    "variant-files.ts"
    "variant-types.ts"
    "variant-schemas.ts"
)

# Track if any files changed
CHANGED=0

echo "Syncing CLI variant utilities..."

for file in "${VARIANT_FILES[@]}"; do
    SOURCE_FILE="$SOURCE_DIR/$file"
    TARGET_FILE="$TARGET_DIR/$file"

    if [ ! -f "$SOURCE_FILE" ]; then
        echo -e "  ${YELLOW}⚠ $file not found in source, skipping${NC}"
        continue
    fi

    # Check if file needs sync (different or doesn't exist)
    if [ ! -f "$TARGET_FILE" ] || ! diff -q "$SOURCE_FILE" "$TARGET_FILE" > /dev/null 2>&1; then
        cp "$SOURCE_FILE" "$TARGET_FILE"
        echo -e "  ${GREEN}✓ Synced $file${NC}"
        CHANGED=1
    else
        echo -e "  - $file (no changes)"
    fi
done

# Create/update index.ts barrel export
INDEX_FILE="$TARGET_DIR/index.ts"
cat > "$INDEX_FILE" << 'EOF'
/**
 * Variant utilities barrel export
 *
 * AUTO-GENERATED by scripts/sync-cli-variants.sh
 * Source of truth: cli/src/utils/variant-*.ts
 *
 * Do not edit this file directly in packages/cli/
 * Edit in cli/src/utils/ and run sync script or commit to auto-sync.
 */

export * from './variant-types.js';
export * from './variant-definitions.js';
export * from './variant-detector.js';
export * from './variant-files.js';
export * from './variant-schemas.js';
EOF
echo -e "  ${GREEN}✓ Updated index.ts${NC}"

# Sync tests if they exist
SOURCE_TESTS="$SOURCE_DIR/__tests__"
TARGET_TESTS="$TARGET_DIR/__tests__"

if [ -d "$SOURCE_TESTS" ]; then
    mkdir -p "$TARGET_TESTS"

    for testfile in "$SOURCE_TESTS"/variant-*.test.ts; do
        if [ -f "$testfile" ]; then
            filename=$(basename "$testfile")
            TARGET_TEST="$TARGET_TESTS/$filename"

            if [ ! -f "$TARGET_TEST" ] || ! diff -q "$testfile" "$TARGET_TEST" > /dev/null 2>&1; then
                cp "$testfile" "$TARGET_TEST"
                echo -e "  ${GREEN}✓ Synced test: $filename${NC}"
                CHANGED=1
            fi
        fi
    done
fi

# If files changed, stage them for commit
if [ "$CHANGED" -eq 1 ]; then
    echo ""
    echo -e "${GREEN}CLI variants synced successfully${NC}"

    # Stage the synced files (for pre-commit hook)
    if git rev-parse --git-dir > /dev/null 2>&1; then
        git add "$TARGET_DIR"/*.ts 2>/dev/null || true
        git add "$TARGET_DIR/__tests__"/*.ts 2>/dev/null || true
        echo -e "${GREEN}Staged synced files for commit${NC}"
    fi
else
    echo ""
    echo "CLI variants already in sync"
fi
