/**
 * Variant utilities barrel export
 *
 * AUTO-GENERATED by scripts/sync-cli-variants.sh
 * Source of truth: cli/src/utils/variant-*.ts
 *
 * Do not edit this file directly in packages/cli/
 * Edit in cli/src/utils/ and run sync script or commit to auto-sync.
 */

export * from './variant-types.js';
export * from './variant-definitions.js';
export * from './variant-detector.js';
export * from './variant-files.js';
export * from './variant-schemas.js';
